### ISSUE TITLE
Root password?

### ISSUE THREAD

**Issue by Z3roCoder** [sonatype/docker-nexus#10]
What is the root-password for the docker container? It would be needed immensely much

**Comment by jswank** [comment]
Hi,

These images use centos:centos7 as a base, so the root password is whatever that uses.

Having to enter a root password for a docker container is a serious anti-pattern; I suggest using these images as a base and performing whatever modifications you need- including something like `RUN echo "root:password" | chpasswd` if truly required.

**Comment by Z3roCoder** [comment]
The thing is, I have to make sure that my container can communicate with the outside internet, and ping is not allowed to be used in the container. I have to say "chmod u+s `which ping`" to even enable ping, but then it requires me to have root-permissions.

**Comment by jswank** [comment]
So the CMD invoked by the container is not `java`?  To try a one-off check of general container communication, it seems as if you could just run `docker run --rm -u root sonatype:nexus ping <whatever>.  To make permanent modifications to an image, just create your own using this as the base:

```
$ cat Dockerfile:
FROM sonatype/nexus
USER root
RUN chmod u+x `which ping`
USER nexus
$ docker build --tag Z3roCoder/nexus .
```

**Comment by dmoore247** [comment]
login to nexus container with user id = 0 (root):
`docker exec -u 0 -it nexus3 bash`
