### ISSUE TITLE
LowDiskSpaceException - based on docker

### ISSUE THREAD

**Issue by CCVIII** [sonatype/docker-nexus#101]
The next error has appeared every few days and Nexus server become unavailable:

300 WARN  [quartz-9-thread-12]  *SYSTEM org.sonatype.nexus.blobstore.file.FileBlobStore - Attempt to access non-existent blob 60cac04a-2ebb-48d8-a55c-a39306e28192 (/nexus-data/blobs/blob01/content/vol-18/chap-28/60cac04a-2ebb-48d8-a55c-a39306e28192.properties)
2021-07-24 22:15:12,616+0300 WARN

**Comment by dawidsawa** [comment]
Hi @CCVIII , unfortunately we do not monitor this GitHub project for issue reports. If you happen to have a Pro license, please report your issue to the support team, or if you're using free OSS license, please use one of the following to seek help:
- [Nexus Users group](https://groups.google.com/a/glists.sonatype.com/g/nexus-users)
- [Nexus Repository Community Forum](https://community.sonatype.com/c/nexus-repository/6)
- or file a report in our [issue tracker](https://issues.sonatype.org/projects/NEXUS/issues)
