### ISSUE TITLE
It upload *.deb file, error msg "Can't find signing key in key ring "

### ISSUE THREAD

**Issue by kervin521** [sonatype/docker-nexus#102]
![image](https://user-images.githubusercontent.com/9798724/146920838-e7efe9ff-fae7-4bbb-b252-f4a4df10b6ae.png)

**Comment by dawidsawa** [comment]
Hi @kervin521, unfortunately we do not monitor this GitHub project for issue reports. If you happen to have a Pro license, please report your issue to the support team, or if you're using free OSS license, please use one of the following to seek help:
- [Nexus Users group](https://groups.google.com/a/glists.sonatype.com/g/nexus-users)
- [Nexus Repository Community Forum](https://community.sonatype.com/c/nexus-repository/6)
- or file a report in our [issue tracker](https://issues.sonatype.org/projects/NEXUS/issues)

**Comment by joedragons** [comment]
Wanted to add, it also seems unlikely this issue is specific to the docker implementation of Nexus Repository.  So, seconding what @dawidsawa says :)

**Comment by kervin521** [comment]
how to use  free OSS license in docker container of Nexus?

**Comment by joedragons** [comment]
@kervin521 OSS version doesn't require a license, unless you're doing something I'm not aware of, then you probably should ask the provider of the license.
