### ISSUE TITLE
How to package config?

### ISSUE THREAD

**Issue by BorePlusPlus** [sonatype/docker-nexus#11]
Hello,

I would like to use you docker image, but would like to use my specific settings (different passwords, clojars, etc.). What is the easiest way to extend your image so that it would use `conf` directory that I would provide.

I have tried something like this:
```Dockerfile
FROM sonatype/nexus:oss

COPY nexus.xml ${SONATYPE_WORK}/conf/
```

but without success.

Thanks

**Comment by steinsag** [comment]
Not fully sure why you need that. Start their image, configure it the way you want and reuse your data directory or container. Of course you should not store any data inside the container itself, but instead use a data container or a directory on the host. But they described that clearly on the setup instructions.

**Comment by mosabua** [comment]
Beyond that I suggest to configure Nexus via the REST API e.g. using the command line utils or a puppet module.

http://books.sonatype.com/nexus-book/reference/_nexus_integrations.html

https://forge.puppetlabs.com/atlassian/nexus_rest

https://github.com/RiotGamesMinions/nexus_cli

**Comment by kellyrob99** [comment]
@BorePlusPlus Hopefully the already provided answers handle your needs, but if not please feel free to add additional comments here.

**Comment by BorePlusPlus** [comment]
Yep, thanks.
