### ISSUE TITLE
Container crashes silently as soon as I deploy to Nexus

### ISSUE THREAD

**Issue by climbupthewalls** [sonatype/docker-nexus#14]
I create a data volume like:
```
$ docker run -d --name nexus-data sonatype/nexus:oss /bin/true
```

Then I create a container with port 8081 open like:
```
$ docker run -d --volumes-from nexus-data --name nexus -e CONTEXT_PATH=/nexus -p 8081:8081 sonatype/nexus:oss
```

I wait for the page to come up at `http://example.com:8081/nexus`. It looks good. Then I proxy incoming traffic to `/nexus` to 8081 in `nginx.conf` like:
```
upstream docker_nexus {
  server example.com:8081;
}

server {
  listen 443;
  // SSL stuff
  // ....
  location /nexus {
    proxy_pass http://docker_nexus/nexus;
     ...
  }
}
```
..and I restart nginx. Nexus is now appearing at `https://example.com/nexus`. Everything looks fine, except I'm warned that the proxy is not working and I should **Force base URL**. I do so, noticing that my the base URL provided lacks the **s** in **https** and is formatted like: `http://example.com/nexus/`. I add the **s** and check **Force Base URL** and click **Save**.

I create a user on the site with every role and a corresponding entry in my `$HOME/.m2/settings.xml` with the same auth info like:
```
<settings>
  <servers>
    <server>
      <id>example.com</id>
      <username>user</username>
      <password>sekrit</password>
    </server>
  </servers>
</settings>
```

I add the default repositories to my project's `pom.xml` like:
```
  <distributionManagement>
    <repository>
      <id>example.com</id>
      <name>Releases</name>
      <url>https://example.com/nexus/content/repositories/releases</url>
    </repository>
    <snapshotRepository>
      <id>example</id>
      <name>Snapshots</name>
      <url>https://example.com/nexus/content/repositories/snapshots</url>
    </snapshotRepository>
  </distributionManagement>
```

When I attempt to deploy my project to the Nexus repository using `mvn deploy`, the container dies silently. The logs reveal no information prior to the event. This is 100% reproducible; I haven't been able to successfully deploy anything yet.

**Comment by steinsag** [comment]
Have you tried without nginx routing just to keep the setup simple and identify the root cause? I've set up the nexus docker image in my company and deployment is working fine. However, I'm just using the default ports on pure http:// without any encryption as it is a purely internal service to us.

**Comment by climbupthewalls** [comment]
I've investigated further. I think we can close this. I was overrunning the RAM on the host machine, which was crashing the JVM. I don't think it's reasonable to expect Nexus to log that kind of event. =P Sorry for the false report!
