### ISSUE TITLE
Add a version for latest Nexus version 3.0 milestone

### ISSUE THREAD

**Issue by dkirrane** [sonatype/docker-nexus#17]
Hi,

Can you provide a docker tag for Nexus 3 milestone 5.

**Comment by mosabua** [comment]
Given that Nexus 3 is largely different we are most likely looking at a separate Docker image.

**Comment by JonaDupIO** [comment]
Hi.

Are you working on it? I would like to test, but if you are not working on it, I will build a container by myself.

**Comment by fthamura** [comment]
this will be interesting, esp to make nexus on docker to manage docker repo/private..

**Comment by WebDucer** [comment]
Would be helpful to test the new Nexus 3 as docker container to plan the migration and to play with new features.

**Comment by stevetarver** [comment]
Would also make upgrading between milestones easier. :+1:

**Comment by mosabua** [comment]
A docker container for v3 is coming. Stay tuned.

**Comment by bargenson** [comment]
Do you have an ETA? We gonna need this image soon and I would like to evaluate if we gonna need to create our own.

Thanks!

**Comment by DarthHater** [comment]
@bargenson @stevetarver @WebDucer  and others, go ahead and check out https://github.com/sonatype/docker-nexus3 which is our new image specifically for Nexus Repository 3.0
