### ISSUE TITLE
Can't find any "docker" related features after installation

### ISSUE THREAD

**Issue by freewind** [sonatype/docker-nexus#19]
I just installed the "docker-nexus" following the documentation, by this command:

```
docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss
```

Then I can open `http://localhost:8081` from browser, and login to nexus successfully. But the problem is I can't find any docker related features.

I tried to add a new proxy repository, but there is no "docker" type as I expected:

![image](https://cloud.githubusercontent.com/assets/333781/11860150/8d25c6f8-a4ac-11e5-8e95-2f7c407e90f1.png)

Do I miss anything?

**Comment by joedragons** [comment]
@freewind The docker related features are only available as part of Nexus 3.  The docker image provided here is of Nexus 2.
See this issue for tracking requests for a docker image for Nexus 3: https://github.com/sonatype/docker-nexus/issues/17.    There is no existing docker image for Nexus 3.
You can find the latest milestone (technology preview) for Nexus 3 in a non-image form here: https://support.sonatype.com/hc/en-us/articles/213466018-Nexus-Repository-Manager-3-0-Technology-Preview-Milestone-6-Release-
Hope that helps.

**Comment by freewind** [comment]
Ah~~ Just realised that this repository is not "nexus with docker proxy supported", but "nexus in a docker image" :smile:
