### ISSUE TITLE
docker hub image is only at version 2.11.2-03

### ISSUE THREAD

**Issue by thomasf** [sonatype/docker-nexus#2]
Maybe image builds aren't being triggered correctly?

Also maybe It's a good idea to tag the patch releases individually so that it's easier to revert to a previous version for whatever reason.

**Comment by kellyrob99** [comment]
Builds updated and tag matching the release version added (2.11.2-06). Hope that meets your needs :)

**Comment by thomasf** [comment]
thanks!
