### ISSUE TITLE
Nexus behind proxy

### ISSUE THREAD

**Issue by nevenr** [sonatype/docker-nexus#27]
Hi,

we use nexus behind web proxy and it would be great if we could configure it in automated fashion via environment variable (http(s)_proxy or java_opts).

Regards,
N.

**Comment by gachen95** [comment]
You can use

		nexus:
			image: sonatype/nexus:2.12.0-01
			environment:
			- CONTEXT_PATH=/nexus

**Comment by mosabua** [comment]
You can update that config via the REST API after it was started. Or you can use the command line.. e.g. check http://books.sonatype.com/nexus-book/reference/community-integrations.html

**Comment by kellyrob99** [comment]
Should be able to do this as described in the README or as @gachen95 has mentioned in a docker-compose file
