### ISSUE TITLE
Why the "FROM dockerfile/java:oracle-java7" ?

### ISSUE THREAD

**Issue by guizmaii** [sonatype/docker-nexus#3]
Hi,

Why do you use this ```dockerfile/java:oracle-java7``` version of Java image and not just the official build : 

```
FROM java:7
```

?

**Comment by davidkarlsen** [comment]
And why not run java8?

**Comment by guizmaii** [comment]
Java 8 could bring compatibility problems if Nexus is not build with Java 7.

For the change to the ```Java:7``` official build, see PR #5

**Comment by jswank** [comment]
Re: the `java` base image. The previous `dockerfile/java:oracle-java7` was deprecated, and the current `java` image does not support Oracle JDK.   Sonatype generally recommends the Oracle JDK for Nexus, which the current `java` image does not support.  

https://support.sonatype.com/entries/24901442-Sonatype-Nexus-System-Requirements

To work around this, the current image now uses `centos:7` as base and installs the Oracle JDK.

Re: Java 8. Java 8 should be used- this update will be coming soon after additional testing.
