### ISSUE TITLE
maybe an issue with nexus, and not specifically the container

### ISSUE THREAD

**Issue by xenoterracide** [sonatype/docker-nexus#36]
I let my docker container autoredeploy from 2.0.13 to 2.0.14, when it does this, I'm getting a 404 from / downgrading to 13 and it works again.

**Comment by alberto-brigandi** [comment]
Seems like the base context path has been changed from `/` to `/nexus` in 4cf8240519b372364440e5bdf840b4d8bb4ef017. Maybe your problem is due to that

**Comment by DarthHater** [comment]
@xenoterracide I believe @alberto-brigandi is absolutely right. The base context path is nexus. This was changed intentionally in #32 . Closing this issue as a result.

**Comment by rmoriz** [comment]
We were also affected by this brutal change we didn't expect…
