### ISSUE TITLE
Image not rebuilding?

### ISSUE THREAD

**Issue by bparees** [sonatype/docker-nexus#40]
This appears to be an automated build on dockerhub, but despite new changes merging recently, it hasn't rebuilt in 23 days: https://hub.docker.com/r/sonatype/nexus/builds/

Can someone force a rebuild/publish?

@oatmealraisin fyi

**Comment by DarthHater** [comment]
@bparees @oatmealraisin hey there! We actually still have it under manual control, primarily so we can test and make sure we have confidence it won't blow up in the wild :)

That said, we should have a new release coming next week.

**Comment by bparees** [comment]
great, thanks
