### ISSUE TITLE
HTTP ERROR: 404

### ISSUE THREAD

**Issue by Aleyasen** [sonatype/docker-nexus#48]
I run docker using the following commands in the tutorial:
```
$ docker run -d --name nexus-data sonatype/nexus echo "data-only container for Nexus"
$ docker run -d -p 8081:8081 --name nexus --volumes-from nexus-data sonatype/nexus
```
but when I open `http://127.0.0.1:8081/`, I got 404 error. 

Error text in browser
------------
HTTP ERROR: 404
Problem accessing /. Reason:
    Not Found
Powered by Jetty://
------------

**Comment by joedragons** [comment]
Try http://localhost:8081/nexus/ ?

**Comment by DarthHater** [comment]
As @joedragons implies, I believe you haven't used the context path (which is nexus by default). Closing this.
