### ISSUE TITLE
dockerhub image verison is out of date

### ISSUE THREAD

**Issue by wenxingyu** [sonatype/docker-nexus#57]
the nexus 2 version is 3 month ago. It does not use the latest java version that support detecting the docker   
 runtime env
[Nexus2 Image](https://hub.docker.com/r/sonatype/nexus/)

**Comment by whyjustin** [comment]
Nexus Docker image is currently up to date. Server JRE updated here https://github.com/sonatype/docker-nexus/pull/67.
