### ISSUE TITLE
404 for JAVA_URL 

### ISSUE THREAD

**Issue by tony--** [sonatype/docker-nexus#64]
Probably due to release of 8u151.
Just need to update some of the ENVs:
    JAVA_VERSION_MINOR=151 \
    JAVA_VERSION_BUILD=12 \
    JAVA_DOWNLOAD_HASH=e758a0de34e24606bca991d704f6dcbf \

**Comment by tony--** [comment]
I can submit a PR if you want one.

**Comment by whyjustin** [comment]
Thanks, fixed and merged via #65. PRs always welcome.
