### ISSUE TITLE
Private DockerHub images not available at Nexus

### ISSUE THREAD

**Issue by leoieggli** [sonatype/docker-nexus#76]
We use a private DockerHub account and we want to use Nexus as a proxy for those private images - we configured the repo following this instructions: http://stevetarver.github.io/2016/11/22/nexus-in-docker.html

By the way, we are not able to view any image from our DockerHub account on Nexus, and the images pushed to our Nexus not appears on DockerHub.

**Comment by mpiggott** [comment]
This repository is for the docker image of Nexus 2.
