### ISSUE TITLE
Use Nexus as a Private Docker Image repository

### ISSUE THREAD

**Issue by robertoandrade** [sonatype/docker-nexus#8]
Given Nexus supports so many other binary repository formats (i.e.: NPM, NuGet, etc, in addition to Maven) was wondering if there was anything available yet to configure it as a potential storage repository for Docker images (private ones) like Docker Registry Hub, Google Container Repository, etc.

**Comment by mosabua** [comment]
Not yet .. but stay tuned. More details at https://issues.sonatype.org/browse/NEXUS-6166 ... keep an eye on Nexus 3.
