### ISSUE TITLE
Does Sonatype Nexus™ 2.5.1-01 version supports docker?

### ISSUE THREAD

**Issue by srkrmandal** [sonatype/docker-nexus#80]
Our organization currently uses Nexus version Sonatype Nexus™ 2.5.1-01. We need to know if this version support as private repository of Docker Images and is there any official support as well.

Thanks,
Srinath

**Comment by joedragons** [comment]
Docker is only available in Nexus Repository Manager 3.  It is highly unlikely (I'd say borderline impossible) we'll implement anything for Nexus Repository Manager 2 as we are forward focused.
I hope that helps!

**Comment by srkrmandal** [comment]
?Thank you so much.


Thanks,

Srinath

________________________________
