### ISSUE TITLE
Issue while upgrading Nexus 2.14.9 to Nexus 3.13

### ISSUE THREAD

**Issue by AnuragCvent** [sonatype/docker-nexus#81]
HI Team,
I am getting the below issue while upgrading Nexus 2.14.9 to Nexus 3.13.

**Failed: java.lang.IllegalStateException: Ingestion method FS_LINK unavailable from repository bt-travel-wildfly to blob store default. Allowed: [[DOWNLOAD]]**

I am blocked because of the above issue. Can you please suggest?

Thanks
Anurag

**Comment by joedragons** [comment]
@AnuragCvent What Transfer method did you choose?  Sounds like you picked (file system) hard link and you connection only allows (HTTP) download.
Ref: https://help.sonatype.com/display/NXRM3/Data+Transfer+Methods
PS: This is not a great place for non-bugs.  For future suggest our user forums 
https://groups.google.com/a/glists.sonatype.com/forum/?hl=en#!forum/nexus-users and community.sonatype.com

**Comment by joedragons** [comment]
From the doc: "This upgrade method works if versions 2 and version 3 are configured to access the same storage system on identically named mount points and hard linking is supported by the file system used."
