### ISSUE TITLE
The sonatype/nexus:oss does not provide a management web-gui following instructions from docker hub.

### ISSUE THREAD

**Issue by inbay** [sonatype/docker-nexus#86]
Following the description on https://hub.docker.com/r/sonatype/nexus/
{
docker pull sonatype/nexus:oss
docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss
}
Provides me with a running container, but without a web gui to manage it at http://localhost:8081
Is a web server/gui included in the nexus container, and if so how can I configure this?

**Comment by inbay** [comment]
Is a web-gui required to be installed in addition to this?

**Comment by collinpeters** [comment]
The UI on Nexus Repository Manager 2 lives at http://localhost:8081/nexus/
Are you able to see this one? I see that isn't explicitly called out in the readme so I'll throw together a quick PR.
