### ISSUE TITLE
Administrator password

### ISSUE THREAD

**Issue by pmury** [sonatype/docker-nexus#91]
How to set admin password for the Docker distribution, or is there a default one?

**Comment by djafaka** [comment]
To change for the first time the admin password follow the following steps (docker version only)
Go to the Nexus container instance for example 91aefe723146
make a docker exec -it 91aefe723146 /bin/bash
Go to /nexus-data
get the password content of the file admin.password
 log again to the admin console and put the password and reinit your password.
Done !

**Comment by ainfosecchimp** [comment]
bash-4.4$ cd nexus-data/
bash-4.4$ ls
etc  log  tmp


:(

no file for me

**Comment by MParvin** [comment]
It's worked for me:
user: admin
password: admin123
