### ISSUE TITLE
yarn scoped packages don't work because cant configure how slashes are interpreted

### ISSUE THREAD

**Issue by airtonix** [sonatype/docker-nexus#97]
see: https://issues.sonatype.org/browse/NEXUS-19709

**Comment by dawidsawa** [comment]
This repository is only for the Docker image of Nexus Repository Manager. If you have an issue with Nexus Repository Manager, and not just how the Docker image behaves or is created, please check and file a ticket in our [bug tracker for NXRM](https://issues.sonatype.org/browse/NEXUS). Also, the linked issue is closed so I assume this is non-issue.
